ignore:
  - "examples"   # No need to cover the examples
  - "src/models" # Examples provide integration testing here
  - "src/deprecations"
  - "src/visualizations"
  - "ext/AgentsVisualizations"
  - "ext/AgentsOSMVisualizations"
  - "ext/AgentsGraphVisualizations"
  - "benchmark"
  - "test"
  - "docs"
  
