[osm_map_gottingen]
git-tree-sha1 = "992999e92c27565d43f947db31dfb78d24cfec73"
lazy = true

    [[osm_map_gottingen.download]]
    url = "https://raw.githubusercontent.com/JuliaDynamics/JuliaDynamics/master/artifacts/agents/osm_map_gottingen.json"
    sha256 = "ba51d233df9c8d4631c8688ab1877c38229f242dc9e209ea98560b6ccf9f23b0"