@deprecate fastest schedule_fastest
@deprecate by_id schedule_by_id
@deprecate as_added schedule_by_id
@deprecate random_activation schedule_randomly
@deprecate partial_activation schedule_partially
@deprecate property_activation schedule_by_property
@deprecate by_type schedule_by_type
